# Generated by Django 5.0.3 on 2024-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressandinfo',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
