# Generated by Django 5.0.3 on 2024-03-28 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_information',
        ),
        migrations.AddField(
            model_name='product',
            name='Description',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Product_information',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
