# Generated by Django 5.0.3 on 2024-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_banner_area_alter_slider_discount_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_area',
            name='Discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
