# Generated by Django 5.0.3 on 2024-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_banner_area_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_area',
            name='Discount',
        ),
        migrations.AddField(
            model_name='banner_area',
            name='Discount_quote',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='discount_deal',
            field=models.CharField(choices=[('New Arraivels', 'New Arraivels'), ('HOT DEALS', 'HOT DEALS')], max_length=100),
        ),
    ]
