# Generated by Django 5.0.3 on 2024-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_slider_discount_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='discount_deal',
            field=models.CharField(choices=[('New Arraivels', 'New Arraivels'), ('HOT DEALS', 'HOT DEALS')], max_length=100),
        ),
    ]
