# Generated by Django 5.0.3 on 2024-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_slider_discount_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='discount_deal',
            field=models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('New Arraivels', 'New Arraivels')], max_length=100),
        ),
    ]
