# Generated by Django 5.0.3 on 2024-03-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main_category',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
